"""
SKYNET Streaming RAG Engine
============================

RAG engine with streaming LLM responses for real-time user feedback.

Features:
- Stream LLM responses as they generate
- Real-time token-by-token output
- Better UX for long answers
- Async streaming with aiohttp
- Compatible with existing RAG

Clearance Level: Omega-Strategic
Classification: CORE INFRASTRUCTURE
"""

import asyncio
import aiohttp
import time
from typing import List, Dict, Any, Optional, AsyncIterator
from pathlib import Path
import json


class StreamingRAGEngine:
    """
    RAG engine with streaming LLM responses.

    Streams tokens as they're generated for better UX.

    Example:
        >>> engine = StreamingRAGEngine()
        >>> async for chunk in engine.query_stream("SQL injection?"):
        ...     print(chunk, end='', flush=True)
    """

    def __init__(
        self,
        vector_db=None,
        llm_config: Optional[Dict] = None,
        use_async_vector_db: bool = True
    ):
        """
        Initialize streaming RAG engine.

        Args:
            vector_db: Vector database instance
            llm_config: LLM configuration
            use_async_vector_db: Use async vector DB
        """
        if use_async_vector_db:
            from .async_vector_db import get_async_vector_db
            self.vector_db = vector_db or get_async_vector_db()
            self.is_async_db = True
        else:
            from .vector_db import get_vector_db
            self.vector_db = vector_db or get_vector_db()
            self.is_async_db = False

        self.llm_config = llm_config or self._load_llm_config()

        # Statistics
        self._stats = {
            "total_streams": 0,
            "total_tokens_streamed": 0,
            "average_latency": 0.0
        }

    def _load_llm_config(self) -> Dict:
        """Load LLM configuration."""
        config_path = Path.home() / ".skynet" / "config.json"
        if config_path.exists():
            with open(config_path) as f:
                return json.load(f)
        return {
            "base_url": "http://localhost:11434",
            "model": "qwen2.5:7b"
        }

    async def query_stream(
        self,
        question: str,
        top_k: int = 5,
        source_filter: Optional[str] = None
    ) -> AsyncIterator[str]:
        """
        Query with streaming LLM response.

        Yields tokens as they're generated by the LLM.

        Args:
            question: Question to answer
            top_k: Number of documents to retrieve
            source_filter: Optional source filter

        Yields:
            Token strings from LLM

        Example:
            >>> async for token in engine.query_stream("What is XSS?"):
            ...     print(token, end='', flush=True)
        """
        self._stats["total_streams"] += 1

        # Build metadata filter
        filter_metadata = None
        if source_filter:
            filter_metadata = {"source": source_filter}

        # Retrieve relevant documents
        if self.is_async_db:
            retrieved_docs = await self.vector_db.query_async(
                query_text=question,
                top_k=top_k,
                filter_metadata=filter_metadata
            )
        else:
            loop = asyncio.get_event_loop()
            retrieved_docs = await loop.run_in_executor(
                None,
                lambda: self.vector_db.query(
                    query_text=question,
                    top_k=top_k,
                    filter_metadata=filter_metadata
                )
            )

        # Build context
        context = self._build_context(retrieved_docs)

        # Generate streaming answer
        async for token in self._generate_answer_stream(question, context):
            yield token

    def _build_context(self, documents: List[Dict]) -> str:
        """Build context string from retrieved documents."""
        if not documents:
            return "No relevant information found."

        context_parts = []
        for i, doc in enumerate(documents, 1):
            source = doc['metadata'].get('source', 'unknown')
            content = doc['content']
            score = doc['score']

            context_parts.append(
                f"[Source {i}: {source} (relevance: {score:.2f})]\n{content}\n"
            )

        return "\n".join(context_parts)

    async def _generate_answer_stream(
        self,
        question: str,
        context: str
    ) -> AsyncIterator[str]:
        """
        Generate streaming answer from LLM.

        Yields tokens as they're generated.

        Args:
            question: User question
            context: Retrieved context

        Yields:
            Token strings
        """
        try:
            prompt = self._create_rag_prompt(question, context)

            timeout = aiohttp.ClientTimeout(total=180)
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(
                    f"{self.llm_config['base_url']}/api/generate",
                    json={
                        "model": self.llm_config.get("model", "qwen2.5:7b"),
                        "prompt": prompt,
                        "stream": True,  # Enable streaming
                        "options": {
                            "temperature": 0.3,
                            "num_predict": 500
                        }
                    }
                ) as response:
                    if response.status == 200:
                        # Stream response line by line
                        async for line in response.content:
                            if line:
                                try:
                                    data = json.loads(line.decode('utf-8'))
                                    token = data.get("response", "")
                                    if token:
                                        self._stats["total_tokens_streamed"] += 1
                                        yield token

                                    # Check if done
                                    if data.get("done", False):
                                        break
                                except json.JSONDecodeError:
                                    continue
                    else:
                        yield f"Error: HTTP {response.status}"

        except asyncio.TimeoutError:
            yield "Error: LLM timeout (>3 minutes)"
        except Exception as e:
            yield f"Error: {str(e)}"

    def _create_rag_prompt(self, question: str, context: str) -> str:
        """Create RAG prompt for LLM."""
        prompt = f"""You are SKYNET, an advanced cybersecurity AI assistant. Answer the question using ONLY the provided context.

**CONTEXT:**
{context}

**QUESTION:**
{question}

**INSTRUCTIONS:**
1. Use ONLY information from the context above
2. If the context doesn't contain the answer, say "I don't have enough information in my knowledge base"
3. Be specific and technical
4. Include relevant CVE numbers, tools, or techniques mentioned
5. Format code snippets with proper syntax if applicable

**ANSWER:**"""

        return prompt

    async def query_full(
        self,
        question: str,
        top_k: int = 5,
        source_filter: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Query with full response (collect all streamed tokens).

        Args:
            question: Question to answer
            top_k: Number of documents
            source_filter: Optional filter

        Returns:
            Dictionary with question, answer, sources
        """
        # Collect all tokens
        tokens = []
        async for token in self.query_stream(question, top_k, source_filter):
            tokens.append(token)

        answer = "".join(tokens)

        # Get sources (run query again to get docs)
        # TODO: Optimize to not query twice
        filter_metadata = {"source": source_filter} if source_filter else None

        if self.is_async_db:
            retrieved_docs = await self.vector_db.query_async(
                query_text=question,
                top_k=top_k,
                filter_metadata=filter_metadata
            )
        else:
            loop = asyncio.get_event_loop()
            retrieved_docs = await loop.run_in_executor(
                None,
                lambda: self.vector_db.query(
                    query_text=question,
                    top_k=top_k,
                    filter_metadata=filter_metadata
                )
            )

        return {
            "question": question,
            "answer": answer,
            "sources": retrieved_docs,
            "streaming": True
        }

    def get_stats(self) -> Dict[str, Any]:
        """Get streaming statistics."""
        return {
            "total_streams": self._stats["total_streams"],
            "total_tokens_streamed": self._stats["total_tokens_streamed"],
            "average_tokens_per_stream": (
                self._stats["total_tokens_streamed"] / self._stats["total_streams"]
                if self._stats["total_streams"] > 0 else 0
            )
        }


# Global instance
_streaming_rag_engine = None


def get_streaming_rag_engine() -> StreamingRAGEngine:
    """Get global streaming RAG engine instance."""
    global _streaming_rag_engine
    if _streaming_rag_engine is None:
        _streaming_rag_engine = StreamingRAGEngine()
    return _streaming_rag_engine


# Convenience function
async def query_knowledge_stream(
    question: str,
    top_k: int = 5,
    source_filter: Optional[str] = None
) -> AsyncIterator[str]:
    """
    Query knowledge base with streaming response.

    Args:
        question: Question to answer
        top_k: Number of documents
        source_filter: Optional filter

    Yields:
        Token strings from LLM

    Example:
        >>> async for token in query_knowledge_stream("What is SQL injection?"):
        ...     print(token, end='', flush=True)
    """
    engine = get_streaming_rag_engine()
    async for token in engine.query_stream(question, top_k, source_filter):
        yield token
