{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kryon.fullname" . }}-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kryon.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
