apiVersion: v1
kind: Service
metadata:
  name: kryon-server
  namespace: kryon-system
  labels:
    app.kubernetes.io/name: kryon
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
  - port: 8700
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: kryon
    app.kubernetes.io/component: server
