"""F202.AE — Genera docs/upstream_skills_diff.md.

Analiza el repo upstream mukul975/Anthropic-Cybersecurity-Skills,
identifica skills banking-relevant que no estan en imported/, y
emite el diff doc.

Uso:
    python scripts/gen_upstream_skills_diff.py \
        --upstream /tmp/upstream-skills/Anthropic-Cybersecurity-Skills \
        --out docs/upstream_skills_diff.md
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", required=True, help="path to cloned upstream repo")
    ap.add_argument("--out", default="docs/upstream_skills_diff.md")
    ap.add_argument(
        "--imported-dir",
        default="src/kryon/skills/playbooks/imported",
    )
    args = ap.parse_args()

    upstream = Path(args.upstream)
    index_path = upstream / "index.json"
    if not index_path.exists():
        raise SystemExit(f"index.json not found at {index_path}")

    data = json.loads(index_path.read_text(encoding="utf-8"))
    skills = data if isinstance(data, list) else data.get("skills", [])

    imported_dir = Path(args.imported_dir)
    imported = (
        {p.stem.lower() for p in imported_dir.glob("*.md")}
        if imported_dir.exists()
        else set()
    )

    categories = {
        "API Security (BANKING-CRITICAL)": ["api", "rest", "graphql", "fapi", "openapi"],
        "PCI-DSS + Compliance": [
            "pci-dss", "pci dss", "soc2", "iso 27001", "iso27001", "hipaa", "gdpr",
        ],
        "SSO / Federation (banking SSO)": [
            "saml", "okta", "azure ad", "federation", "sso", "oauth", "openid",
        ],
        "K8s Banking Workloads": ["kubernetes", "k8s", "rbac", "helm", "istio"],
        "SAST / DevSecOps": [
            "sast", "semgrep", "codeql", "trivy", "snyk", "devsecops", "github advanced",
        ],
        "Fraud / BEC / Ransomware": [
            "fraud", "bec", "business email", "phishing", "ransomware",
        ],
        "Cloud Banking (AWS/Azure/GCP)": [
            "aws", "azure", "gcp", "iam", "s3", "imds", "cloudtrail", "guardduty",
        ],
        "Forensics / DFIR": [
            "forensics", "memory dump", "volatility", "autopsy", "disk image",
        ],
        "Threat Intel / Hunting": [
            "threat intel", "threat hunt", "yara", "sigma", "mitre", "att&ck",
        ],
    }

    def match_cat(s: dict, keywords: list[str]) -> bool:
        txt = (s.get("name", "") + " " + s.get("description", "")).lower()
        return any(k in txt for k in keywords)

    lines: list[str] = []
    lines.append("# Upstream Skills Diff — Anthropic-Cybersecurity-Skills")
    lines.append("")
    lines.append(
        "**Source**: https://github.com/mukul975/Anthropic-Cybersecurity-Skills (Apache 2.0)"
    )
    lines.append(f"**Upstream total**: {len(skills)} skills")
    lines.append(f"**Imported en Kryon**: {len(imported)} skills (in `imported/`)")
    lines.append("")
    lines.append("Generated by `scripts/gen_upstream_skills_diff.py`. Re-run when upstream updates.")
    lines.append("")
    lines.append("## Top categorias banking-relevant")
    lines.append("")

    for cat, kws in categories.items():
        matches = [s for s in skills if match_cat(s, kws)]
        if not matches:
            continue
        lines.append(f"### {cat} ({len(matches)} upstream)")
        lines.append("")
        for s in matches[:10]:
            name = s.get("name", "")
            desc = (s.get("description", "") or "")[:90]
            lines.append(f"- `{name}` — {desc}")
        lines.append("")

    lines.append("## F202.AF candidates (top 10 banking-relevant)")
    lines.append("")
    candidates = [
        ("testing-api-security-with-owasp-top-10", "API banking auditing"),
        ("implementing-pci-dss-compliance-controls", "augment PCI-DSS audit"),
        ("auditing-kubernetes-cluster-rbac", "banking K8s workloads"),
        ("building-identity-federation-with-saml-azure-ad", "banking SSO"),
        ("implementing-saml-sso-with-okta", "banking SSO"),
        ("securing-api-gateway-with-aws-waf", "API banking edge"),
        ("detecting-business-email-compromise", "BEC fraud detection"),
        ("implementing-semgrep-for-custom-sast-rules", "SAST augment for CWE skills"),
        ("integrating-sast-into-github-actions-pipeline", "CI/CD seguro"),
        ("implementing-devsecops-security-scanning", "pipeline security"),
    ]
    for i, (name, rationale) in enumerate(candidates, 1):
        lines.append(f"{i}. `{name}` — {rationale}")
    lines.append("")

    lines.append("## Transformer requerido (upstream → Kryon format)")
    lines.append("")
    lines.append("Upstream frontmatter: `name`, `description`, `domain`, `subdomain`, `tags`, `version`, `author`, `license`, `nist_csf`.")
    lines.append("")
    lines.append("Kryon frontmatter: `name`, `description`, `triggers (tech/ports/keywords)`, `priority`, `required_tools`.")
    lines.append("")
    lines.append("Mapeo:")
    lines.append("")
    lines.append("- upstream `tags[]` → Kryon `triggers.keywords[]` (auto-extender con sinónimos)")
    lines.append("- upstream `subdomain` → keyword adicional (`web-application-security` → `webapp`)")
    lines.append("- `priority`: banking-critical = 5, genérico = 15")
    lines.append("- Apache-2.0 attribution preservado en el body header")
    lines.append("- `nist_csf` preservado como meta-info en body")
    lines.append("")

    lines.append("## NO importar (out of scope Kryon banking-LATAM)")
    lines.append("")
    lines.append("- Mobile malware analysis (apktool, dex)")
    lines.append("- IoT/firmware reverse engineering")
    lines.append("- Mac-specific forensics")
    lines.append("- ICS/SCADA")
    lines.append("- Generic forensics ya cubiertos en `imported/forensics.md`")
    lines.append("")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {out_path} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
