"""
KRYON Streaming RAG Engine
============================

RAG engine with streaming LLM responses for real-time user feedback.

Features:
- Stream LLM responses as they generate
- Real-time token-by-token output
- Better UX for long answers
- Async streaming with aiohttp
- Compatible with existing RAG

Clearance Level: Omega-Strategic
Classification: CORE INFRASTRUCTURE
"""

import asyncio
import os
from collections.abc import AsyncIterator
from typing import Any


class StreamingRAGEngine:
    """
    RAG engine with streaming LLM responses.

    Streams tokens as they're generated for better UX.

    Example:
        >>> engine = StreamingRAGEngine()
        >>> async for chunk in engine.query_stream("SQL injection?"):
        ...     print(chunk, end='', flush=True)
    """

    def __init__(self, vector_db=None, llm_config: dict | None = None, use_async_vector_db: bool = True):
        """
        Initialize streaming RAG engine.

        Args:
            vector_db: Vector database instance
            llm_config: LLM configuration
            use_async_vector_db: Use async vector DB
        """
        if use_async_vector_db:
            from .async_vector_db import get_async_vector_db

            self.vector_db = vector_db or get_async_vector_db()
            self.is_async_db = True
        else:
            from .vector_db import get_vector_db

            self.vector_db = vector_db or get_vector_db()
            self.is_async_db = False

        self.llm_config = llm_config or self._load_llm_config()

        # Statistics
        self._stats = {"total_streams": 0, "total_tokens_streamed": 0, "average_latency": 0.0}
        self._stats_lock = asyncio.Lock()

    def _load_llm_config(self) -> dict:
        """Load LLM configuration from environment variables.

        RAG generation prefers KRYON_RAG_MODEL (a fast non-thinking model like
        deepseek-chat) so retrieval queries don't burn reasoning tokens.
        """
        return {
            "api_key": os.getenv("OPENAI_API_KEY", ""),
            "base_url": os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
            "model": os.getenv("KRYON_RAG_MODEL", os.getenv("KRYON_MODEL", "gpt-4o")),
        }

    async def query_stream(
        self, question: str, top_k: int = 5, source_filter: str | None = None
    ) -> AsyncIterator[str]:
        """
        Query with streaming LLM response.

        Yields tokens as they're generated by the LLM.

        Args:
            question: Question to answer
            top_k: Number of documents to retrieve
            source_filter: Optional source filter

        Yields:
            Token strings from LLM

        Example:
            >>> async for token in engine.query_stream("What is XSS?"):
            ...     print(token, end='', flush=True)
        """
        async with self._stats_lock:
            self._stats["total_streams"] += 1

        # Build metadata filter
        filter_metadata = None
        if source_filter:
            filter_metadata = {"source": source_filter}

        # Retrieve relevant documents
        if self.is_async_db:
            retrieved_docs = await self.vector_db.query_async(
                query_text=question, top_k=top_k, filter_metadata=filter_metadata
            )
        else:
            loop = asyncio.get_event_loop()
            retrieved_docs = await loop.run_in_executor(
                None,
                lambda: self.vector_db.query(query_text=question, top_k=top_k, filter_metadata=filter_metadata),
            )

        # Build context
        context = self._build_context(retrieved_docs)

        # Generate streaming answer
        async for token in self._generate_answer_stream(question, context):
            yield token

    def _build_context(self, documents: list[dict]) -> str:
        """Build context string from retrieved documents."""
        if not documents:
            return "No relevant information found."

        context_parts = []
        for i, doc in enumerate(documents, 1):
            source = doc["metadata"].get("source", "unknown")
            content = doc["content"]
            score = doc["score"]

            context_parts.append(f"[Source {i}: {source} (relevance: {score:.2f})]\n{content}\n")

        return "\n".join(context_parts)

    async def _generate_answer_stream(self, question: str, context: str) -> AsyncIterator[str]:
        """
        Generate streaming answer from LLM.

        Yields tokens as they're generated.

        Args:
            question: User question
            context: Retrieved context

        Yields:
            Token strings
        """
        try:
            from openai import AsyncOpenAI

            prompt = self._create_rag_prompt(question, context)

            client = AsyncOpenAI(
                api_key=self.llm_config["api_key"],
                base_url=self.llm_config["base_url"],
            )
            stream = await client.chat.completions.create(
                model=self.llm_config.get("model", "gpt-4o"),
                messages=[
                    {"role": "system", "content": "You are KRYON, an advanced cybersecurity AI assistant."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,
                max_tokens=500,
                stream=True,
            )

            async for chunk in stream:
                if chunk.choices and chunk.choices[0].delta.content:
                    token = chunk.choices[0].delta.content
                    async with self._stats_lock:
                        self._stats["total_tokens_streamed"] += 1
                    yield token

        except asyncio.TimeoutError:
            yield "Error: LLM timeout (>3 minutes)"
        except Exception as e:
            yield f"Error: {str(e)}"

    def _create_rag_prompt(self, question: str, context: str) -> str:
        """Create RAG prompt for LLM."""
        prompt = f"""You are KRYON, an advanced cybersecurity AI assistant. Answer the question using ONLY the provided context.

**CONTEXT:**
{context}

**QUESTION:**
{question}

**INSTRUCTIONS:**
1. Use ONLY information from the context above
2. If the context doesn't contain the answer, say "I don't have enough information in my knowledge base"
3. Be specific and technical
4. Include relevant CVE numbers, tools, or techniques mentioned
5. Format code snippets with proper syntax if applicable

**ANSWER:**"""

        return prompt

    async def query_full(self, question: str, top_k: int = 5, source_filter: str | None = None) -> dict[str, Any]:
        """
        Query with full response (collect all streamed tokens).

        Args:
            question: Question to answer
            top_k: Number of documents
            source_filter: Optional filter

        Returns:
            Dictionary with question, answer, sources
        """
        # Collect all tokens
        tokens = []
        async for token in self.query_stream(question, top_k, source_filter):
            tokens.append(token)

        answer = "".join(tokens)

        # Get sources (run query again to get docs)
        filter_metadata = {"source": source_filter} if source_filter else None

        if self.is_async_db:
            retrieved_docs = await self.vector_db.query_async(
                query_text=question, top_k=top_k, filter_metadata=filter_metadata
            )
        else:
            loop = asyncio.get_event_loop()
            retrieved_docs = await loop.run_in_executor(
                None,
                lambda: self.vector_db.query(query_text=question, top_k=top_k, filter_metadata=filter_metadata),
            )

        return {
            "question": question,
            "answer": answer,
            "sources": retrieved_docs,
            "streaming": True,
        }

    async def get_stats(self) -> dict[str, Any]:
        """Get streaming statistics."""
        async with self._stats_lock:
            return {
                "total_streams": self._stats["total_streams"],
                "total_tokens_streamed": self._stats["total_tokens_streamed"],
                "average_tokens_per_stream": (
                    self._stats["total_tokens_streamed"] / self._stats["total_streams"]
                    if self._stats["total_streams"] > 0
                    else 0
                ),
            }


# Global instance
_streaming_rag_engine = None
_streaming_rag_engine_lock = __import__("threading").Lock()


def get_streaming_rag_engine() -> StreamingRAGEngine:
    """Get global streaming RAG engine instance."""
    global _streaming_rag_engine
    if _streaming_rag_engine is None:
        with _streaming_rag_engine_lock:
            if _streaming_rag_engine is None:
                _streaming_rag_engine = StreamingRAGEngine()
    return _streaming_rag_engine


# Convenience function
async def query_knowledge_stream(
    question: str, top_k: int = 5, source_filter: str | None = None
) -> AsyncIterator[str]:
    """
    Query knowledge base with streaming response.

    Args:
        question: Question to answer
        top_k: Number of documents
        source_filter: Optional filter

    Yields:
        Token strings from LLM

    Example:
        >>> async for token in query_knowledge_stream("What is SQL injection?"):
        ...     print(token, end='', flush=True)
    """
    engine = get_streaming_rag_engine()
    async for token in engine.query_stream(question, top_k, source_filter):
        yield token
