"""Environment file writer for first-run setup."""

from __future__ import annotations

import secrets
from pathlib import Path

_KRYON_DIR = Path.home() / ".kryon"

_ENV_TEMPLATE = """\
# KRYON Server Configuration
# Generated by setup wizard

# JWT Authentication
KRYON_JWT_SECRET={jwt_secret}

# API Keys (comma-separated, leave empty for JWT-only auth)
KRYON_API_KEYS=

# CORS Origins (comma-separated)
KRYON_CORS_ORIGINS={cors_origins}

# Debug mode (0=production, 1=debug)
KRYON_DEBUG=0

# Rate limiting (requests per minute)
KRYON_RATE_LIMIT_RPM=60

# Server
KRYON_HOST=0.0.0.0
KRYON_PORT=8700
"""


def generate_jwt_secret() -> str:
    """Generate a cryptographically secure JWT secret."""
    return secrets.token_urlsafe(32)


def write_env_file(
    jwt_secret: str | None = None,
    cors_origins: str = "http://localhost:5173,http://localhost:8700",
    env_dir: Path | None = None,
) -> Path:
    """Write a .env file to the KRYON config directory.

    Returns the path to the written file.
    """
    target_dir = env_dir or _KRYON_DIR
    target_dir.mkdir(parents=True, exist_ok=True)

    if jwt_secret is None:
        jwt_secret = generate_jwt_secret()

    content = _ENV_TEMPLATE.format(
        jwt_secret=jwt_secret,
        cors_origins=cors_origins,
    )

    env_path = target_dir / ".env"
    env_path.write_text(content, encoding="utf-8")
    return env_path
